name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        description: 'A username to greet'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello, ${{ inputs.username }}!"
